services:
  - type: web
    name: wad-mini-project
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeployTrigger: commit
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 22
